# Theme settings
tok:
    baseurl:
    title: Lynx - A Fast, Secure and Reliable Terraform Backend
    theme_color: '#3b82f6'
    language: en-US
    header:
        logo:
            text: Lynx
            image:
        nav:
            - item_name: Homepage
              item_url: /
            - item_name: Documentation
              item_url: /documentation
    footer:
        logo:
            text: Lynx
            image:
        text: Originally created by Clivern. Maintained by Muon Space.
    google_analytics:
        tracking_code:
    comments:
        disqus_forum_shortname:

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# Jekyll settings
permalink: /:title/
remote_theme: clivern/tokyo
